# Generated by Django 4.0.10 on 2024-02-18 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DL',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('downloaded', models.IntegerField(default=0)),
                ('total', models.IntegerField(default=0)),
                ('eta', models.IntegerField(default=0)),
                ('speed', models.FloatField(default=0.0)),
                ('elapsed', models.FloatField(default=0.0)),
                ('downloading', models.BooleanField(default=True)),
                ('error', models.CharField(max_length=64)),
            ],
        ),
    ]
