# Generated by Django 4.0.10 on 2024-02-18 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dl', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DL',
            new_name='DownloadEntries',
        ),
    ]
