# Generated by Django 4.0.10 on 2024-02-18 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dl', '0002_rename_dl_downloadentries'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadentries',
            name='title',
            field=models.CharField(default='None', max_length=128),
        ),
    ]
