# Generated by Django 4.0.10 on 2024-02-18 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dl', '0003_downloadentries_title'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DownloadEntries',
            new_name='Plates',
        ),
    ]
