# Generated by Django 4.0.10 on 2024-02-19 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dl', '0005_plates_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plates',
            name='downloading',
            field=models.BooleanField(default=False),
        ),
    ]
