# Generated by Django 4.0.10 on 2024-02-20 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dl', '0007_plates_paused'),
    ]

    operations = [
        migrations.AddField(
            model_name='plates',
            name='filename',
            field=models.CharField(default='None', max_length=256),
        ),
    ]
