# Generated by Django 4.0.10 on 2024-02-20 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dl', '0008_plates_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='plates',
            name='options',
            field=models.CharField(default='None', max_length=128),
        ),
    ]
