# Generated by Django 4.0.10 on 2024-02-21 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dl', '0009_plates_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='plates',
            name='video_id',
            field=models.CharField(default='None', max_length=64),
        ),
    ]
