# Generated by Django 4.0.10 on 2024-02-21 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dl', '0010_plates_video_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='plates',
            name='format',
            field=models.CharField(default='None', max_length=128),
        ),
    ]
