# Generated by Django 4.0.10 on 2024-02-21 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dl', '0011_plates_format'),
    ]

    operations = [
        migrations.AddField(
            model_name='plates',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
