# Generated by Django 4.0.10 on 2024-02-21 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dl', '0012_plates_done'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preferences',
            fields=[
                ('name', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('value', models.CharField(default='', max_length=1024)),
            ],
        ),
    ]
