# Generated by Django 4.0.10 on 2024-02-22 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dl', '0013_preferences'),
    ]

    operations = [
        migrations.AddField(
            model_name='preferences',
            name='description',
            field=models.CharField(default='', max_length=1024),
        ),
    ]
