# Generated by Django 4.0.10 on 2024-02-26 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dl', '0015_ytdlpconfigs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ytdlpconfigs',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
