# Generated by Django 4.0.10 on 2024-02-26 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dl', '0016_alter_ytdlpconfigs_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='YtdlpConfigs',
            new_name='YtdlpPresets',
        ),
    ]
