# Generated by Django 4.0.10 on 2024-02-26 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dl', '0020_remove_preferences_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='preferences',
            old_name='embed_info_json',
            new_name='embed_json_info',
        ),
    ]
