# Generated by Django 4.0.10 on 2024-02-26 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dl', '0021_rename_embed_info_json_preferences_embed_json_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='preferences',
            name='embed_thumbnail',
            field=models.BooleanField(default=False),
        ),
    ]
