# Generated by Django 4.0.10 on 2024-02-27 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dl', '0022_preferences_embed_thumbnail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Plates',
        ),
    ]
