# Generated by Django 4.0.10 on 2024-02-27 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dl', '0023_delete_plates'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plates',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('owner', models.CharField(default='', max_length=150)),
                ('video_id', models.CharField(default='None', max_length=64)),
                ('title', models.CharField(default='None', max_length=128)),
                ('options', models.CharField(default='None', max_length=128)),
                ('format', models.CharField(default='None', max_length=128)),
                ('filename', models.CharField(default='None', max_length=256)),
                ('thumbnail', models.CharField(default='None', max_length=512)),
                ('downloaded', models.IntegerField(default=0)),
                ('total', models.IntegerField(default=0)),
                ('eta', models.IntegerField(default=0)),
                ('speed', models.FloatField(default=0.0)),
                ('elapsed', models.FloatField(default=0.0)),
                ('done', models.BooleanField(default=False)),
                ('downloading', models.BooleanField(default=False)),
                ('paused', models.BooleanField(default=False)),
                ('error', models.CharField(max_length=64)),
            ],
        ),
    ]
