# Generated by Django 4.0.10 on 2024-02-27 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dl', '0026_alter_plates_error'),
    ]

    operations = [
        migrations.AddField(
            model_name='plates',
            name='has_vcodec',
            field=models.BooleanField(default=False),
        ),
    ]
